import { render, screen } from '@testing-library/react';
import { describe, it, expect, vi } from 'vitest';
import RootLayout, { metadata } from './layout';

vi.mock('next/font/google', () => ({
  Geist: () => ({ variable: '--font-geist-sans', className: 'geist-sans' }),
  Geist_Mono: () => ({ variable: '--font-geist-mono', className: 'geist-mono' }),
}));

// globals.css is not processable by jsdom
vi.mock('./globals.css', () => ({}));

describe('RootLayout', () => {
  it('renders children', () => {
    render(
      <RootLayout>
        <div>Test child</div>
      </RootLayout>
    );
    expect(screen.getByText('Test child')).toBeInTheDocument();
  });

  it('sets the html lang attribute to en', () => {
    const { container } = render(
      <RootLayout>
        <span />
      </RootLayout>
    );
    // next/font mocks return variables; jsdom represents the outer element
    const html = container.querySelector('html') ?? document.documentElement;
    expect(html).toHaveAttribute('lang', 'en');
  });

  it('applies antialiased class to body', () => {
    const { container } = render(
      <RootLayout>
        <span />
      </RootLayout>
    );
    const body = container.querySelector('body') ?? document.body;
    expect(body.className).toContain('antialiased');
  });
});

describe('metadata', () => {
  it('has the correct title', () => {
    expect(metadata.title).toBe('Create Next App');
  });

  it('has the correct description', () => {
    expect(metadata.description).toBe('Generated by create next app');
  });
});
